### PR TITLE
Devices: Add HLTE/HLTECHN/HLTEKOR/HLTETMO

### PR DESCRIPTION
**Pull request by Jprimero15**
* This are Samsung Galaxy note 3 Snapdragon Variants

Signed-off-by: Joshua Primero <jprimero155@gmail.com>

### CODE REVIEW

**Comment by Dyneteve** [comment]
@Jprimero15 1 2 3 4 578

**Comment by hugwalk** [comment]
@Dyneteve what if they release a nota 3 without 4g
what will the codename be

**Comment by Dyneteve** [comment]
@hugwalk HTMO idk

**Comment by hugwalk** [comment]
@Dyneteve must be "h" then

**Pull request merged**
