### PR TITLE
pyxis: 03/11/2024 update

### PR DESCRIPTION
**Pull request by czarsuperstar**

### CODE REVIEW

**Comment by AnierinBliss** [comment]
Does this device have an XDA thread?

**Comment by czarsuperstar** [comment]
Not for A14

**Comment by AnierinBliss** [comment]
> Not for A14

Can you update your 13 one to 14 using the template in this repo? Or create a new one for 14 and close your 13 one?

**Comment by czarsuperstar** [comment]
ok

**Comment by czarsuperstar** [comment]
https://xdaforums.com/t/rom-u-official-evolution-x-for-xiaomi-mi-9-lite-cc9-pyxis.4661359/

**Pull request merged**
